### ISSUE TITLE
HANA DB verification mis-spelled

### ISSUE THREAD

**Issue by trstroem** [sanjeevkumar761/one_touch_sap_deployment_on_azure#2]
Under HANA DB verification, step 5, the command "sapcontrol -nr 00 -Function GetProcessList" must be spelled "sapcontrol -nr 00 -function GetProcessList" (lowercase "f" in the command "function". Otherwise, it fails.

**Comment by sanjeevkumar761** [comment]
Fixed the issue. Now, it is "sapcontrol -nr 00 -function GetProcessList" in README file.
